### ISSUE TITLE
Pod install not work

### ISSUE THREAD

**Issue by zhuyifan2013** [netbeast/react-native-ssdp#10]
There is no podspec under node_modules/react-native-udp'  and there is no node_modules/react-native-network-info,  please make sure this .

pod 'RNUDP', :path => './node_modules/react-native-udp'
pod 'RNNetworkInfo', :path => './node_modules/react-native-network-info'

**Comment by jsdario** [comment]
Hi @zhuyifan2013.
Sadly we are not maintining a Podfile version along this. However we can admit and merge PRs that are tested. Feel free to submit one.
