### ISSUE TITLE
I can not get the example to work

### ISSUE THREAD

**Issue by roberto-chan** [netbeast/react-native-ssdp#15]
I am trying to get the client example to work.  ( I am using a Samsung S7 and the emulator ) neither of them works. 

I follow all of it and also follow the fix for network-info (NetworkInfo.getIPAddress)

but when I run the client sample all I see is

07-28 19:48:31.499  3037  3078 I ReactNativeJS: 'socket-1', 'binding, address:', '0.0.0.0', 'port:', 0

07-28 19:48:31.507  3037  3078 I ReactNativeJS: 'socket-1', 'bound to address:', '0.0.0.0', 'port:', 0

07-28 19:48:41.517  3037  3078 I ReactNativeJS: 'socket-1', 'closing'

07-28 19:48:41.520  3037  3078 I ReactNativeJS: 'socket-1', 'closed'

I got plenty of upnp devices also downloaded http://www.meshcommander.com/upnptools

those tools do see my upnp devices

any hints on how to trouble shoot it ? 

Thanks

**Comment by roberto-chan** [comment]
It is working, sorry for the noobness

**Comment by jsdario** [comment]
We're here to help, glad to know it's working :) @rchanbob

**Comment by roberto-chan** [comment]
Thank you Jesus,

Awesome work.

by the way if you use the latest library things are coming back as
Unit8Array.

so I changed react-native-ssdp/index.js
I updated this to msg = msg.tostring() to msg = new
TextDecoder("utf-8").decode(msg)


SSDP.prototype._parseMessage = function (msg, rinfo) {
msg = new TextDecoder("utf-8").decode(msg);

this._logger('Multicast message: %o', {message: msg});

var type = msg.split('\r\n').shift()
// HTTP/#.# ### Response to M-SEARCH
if (httpHeader.test(type)) {
this._parseResponse(msg, rinfo)
} else {
this._parseCommand(msg, rinfo)
}
}



Thanks for the great library!

Roberto

**Comment by DeepakM02** [comment]
@jsdario, @roberto-chan  how did you use this package. Still, I am getting errors. Unable to find out the way to use this package.
