### ISSUE TITLE
Publish version 2.8.2 to npm

### ISSUE THREAD

**Issue by nim23** [netbeast/react-native-ssdp#16]
Hi there,

I was wondering if you would be able to publish the latest version `2.8.2` to `npm`. Plus thanks for open sourcing this lib.

Nimesh

**Comment by jsdario** [comment]
Just did!

Thanks for the reminder. Normally I'd just use packages pointing at their repo master branch, to avoid using older versions.

Like this in your package.json:

```
react-native-ssdp": "netbeast/react-native-ssdp"
```

**Comment by nim23** [comment]
That was quick. Thanks. Going to try your tip on going forward.
