### ISSUE TITLE
Galaxy S7 is not receiving UDP messages

### ISSUE THREAD

**Issue by roberto-chan** [netbeast/react-native-ssdp#17]
I can send UDP messages but I can not receive any UDP message on my galaxy 7 device.  

I can see the messages with wireshark.  anyone got this running on a Galaxy S7 ? 

I am trying to get other devices to test.   besides using react-native-ssdp, I also tested it with using react-native-udp same issue.  I can send but not receive messages.

**Comment by jsdario** [comment]
This is one of the issues we encountered: https://github.com/tradle/react-native-udp/issues/46, it might be related to your problem

**Comment by brkrtp** [comment]
+1 not work android but work ios
