### ISSUE TITLE
Documentation: Mention that it doesn't work in Android Emulator

### ISSUE THREAD

**Issue by lukewis** [netbeast/react-native-ssdp#19]
This library works great on my android phone, but I wasted a good bit of time  trying to get it working in the Android emulator.  Eventually I found this [https://github.com/ConnectSDK/Connect-SDK-Android/issues/280](url), which seems to indicate that a limitation of the Android emulator doesn't allow incoming multicast udp traffic.  Might be worth a short blurb on the Readme.md to save some others some wasted time.

**Comment by jsdario** [comment]
Absolutely. This is great. Do you want to submit a PR yourself?
