### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by shubham-srivastava-goku** [netbeast/react-native-ssdp#21]
I am getting below error while building the application.

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\ReactApps\Duo\node_modules\react-native-network-info\android\buil
d.gradle' line: 4

* What went wrong:
A problem occurred evaluating project ':react-native-network-info'.
> Could not find method google() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

I've followed every steps as written on the description.
Please help me to resolve it.

Thnaks in advance

**Comment by jsdario** [comment]
You may need to install this package: https://github.com/pusherman/react-native-network-info

**Comment by shubham-srivastava-goku** [comment]
I already installed that.
Here is my package.json dependencies.
"dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-elements": "^0.19.1",
    "react-native-network-info": "^3.2.2",
    "react-native-ssdp": "^2.8.2",
    "react-native-udp": "^2.3.1",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.0.1"
  }

**Comment by jsdario** [comment]
Did you use `react-native link react-native-network-info`?

**Comment by shubham-srivastava-goku** [comment]
I have done all these three after installing them

react-native link react-native-network-info
react-native link react-native-udp
react-native link react-native-ssdp

**Comment by shubham-srivastava-goku** [comment]
The issue was with gradle version. After updating gradle version to 3.1.0, it started working.

**Comment by jsdario** [comment]
Thanks for opening an issue!
