### ISSUE TITLE
Usage with expo

### ISSUE THREAD

**Issue by zwhitchcox** [netbeast/react-native-ssdp#28]
Hi, I'm trying to integrate this project with [expo](https://expo.io), but it seems that the structure of that apps are quite a bit different...I was wondering if you could add expo-specific instructions to the docs? I'm pretty new to react native as it is, and it's kind of hard to figure this stuff out

**Comment by zwhitchcox** [comment]
So, this is actually not compatible with expo, as they don't let you run custom native modules...still might be nice to put that in the docs though

**Comment by dudewheresmycode** [comment]
For anyone else that stumbles upon this and wants to try and get this library working with an expo managed project, you can use the expo [config-plugins](https://docs.expo.dev/config-plugins/introduction/) to make the modifications needed for iOS files. I haven't done Android yet, but will post a solution for that if I find one.

Create the plugin in your project root

`./ssdp-plugin.js`:

```javascript

const path = require('path');
const fs = require( 'fs' )
const { withPlugins, withMod, withDangerousMod } = require('expo/config-plugins');
const {
  mergeContents,
} = require("@expo/config-plugins/build/utils/generateCode");

const POD_LINES = `
  pod 'react-native-udp', :path => './node_modules/react-native-udp'
  pod 'react-native-network-info', :path => './node_modules/react-native-network-info'
`;

async function readFile( path ) {
  return fs.promises.readFile( path, 'utf8' )
}

async function saveFile( path, content ) {
  return fs.promises.writeFile( path, content, 'utf8' )
}

function addPodDepsToTargets(src) {
  return mergeContents({
    tag: `with-ssdp-deps-to-target`,
    src,
    newSrc: POD_LINES.trim(),
    anchor: /target ['"]([^'"]*)['"] do/,
    offset: 2,
    comment: "#",
  }).contents;
}

const withSSDP = (config) => {
  return withPlugins(config, [ (config) => {
    return withDangerousMod( config, [
      'ios',
      async (config) => {
        const file = path.join( config.modRequest.platformProjectRoot, 'Podfile' )
        const contents = await readFile( file );
        await saveFile(file, addPodDepsToTargets(contents))
        return config
      }
    ])
  }]);
};

module.exports = withSSDP;
```

In your `app.config.js`  / `app.json`:

```javascript
plugins: [
  ...
  "./ssdp-plugin.js",
]
```
