### ISSUE TITLE
Cannot plugin

### ISSUE THREAD

**Issue by duydatpham** [netbeast/react-native-ssdp#8]
Hi bro, when i install this lib then run my project. I have a problem.
pls help me :)

I used:
"react": "15.4.2",
"react-native": "0.42.0"

Thanks

![image](https://cloud.githubusercontent.com/assets/5369097/23495392/09375578-ff4b-11e6-8fd6-876a8bf03476.png)

**Comment by jsdario** [comment]
Something like this

https://github.com/netbeast/react-native-ssdp/commits/master

should fix it.

It does not crash on my fork anyway. Please come back if it is not solved.
